module.exports = {
    CAMERA_WIDTH: 35,
    CAMERA_HEIGHT: 26,
    MAP_WIDTH: 1000,
    MAP_HEIGHT: 1000,
    MOVE_SPEED: 100,
    TICK_RATE: 100,
    INVENTORY_WIDTH: 8,
    INVENTORY_HEIGHT: 4,
    CONSOLE_HISTORY: 10
}
